spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/assignment
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8081

security:
  jwt:
    secret: 4oCYc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWNyb3F1aXMtYXNzaWdubWVudC1iYWNrZW5kLWRvY3VtZW50LWFwcHJvdmFsLWRhbmFyeXXigJkK